version: '3.8'
services:
  frontend:
    build:
      context: ../desksetup-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../desksetup-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/desksetuppro-db
    depends_on:
      - mongo


  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
